### ISSUE TITLE
Season 9 is coming!!

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#136]
Season 9 is now ready to go at Minnesota! All the images are in their usual places on the UMN MSI servers, and I have a csv file that tells us which images to grab, as well as defines capture events, provides corrected date/times etc here: https://drive.google.com/open?id=0Bxc_8RhRnC8dbVQxaTExbHFueUU

I assume @parrish is still the one handling the heavy lifting for getting the images out of MSI and into Zooniverse? Though @astopy you might also be involved. The process should be identical to S8, though we've added an extra column called "include" that has a value of 1 for any image that should be pulled into Zooniverse, and 0 for any image that should be excluded.

As with Season 8, we've extracted and cleaned the time-stamps, and already lumped images into capture events (specified in the capture column). The Path column gives the file location, relative to /home/packerc/shared/S9 (e.g. S9/B03/B03_R1/S9_B03_R1_IMAG0001.JPG).

The most difficult part of the whole thing might be trying to remember how to get access to MSI...

**Comment by astopy** [comment]
I’m pretty sure I did this last time, not that I can remember exactly how. If we can get login details for MSI then I’ll take a look.

**Comment by aliburchard** [comment]
@astopy I remember getting login details was a pain. Whereas we had previously used one for "zooniverse", MSI cracked down on sharing logins and you (I assume) had to request a 'personal' one. Not sure where we saved that information...

**Comment by astopy** [comment]
Looking back through email from last time I think we either just used your account or Arfon’s old account, but I’m not sure which. I don’t think we managed to get into the old shared zooniverse account.

**Comment by mkosmala** [comment]
I can set up a new account. Just let me know what login name you want.

**Comment by aliburchard** [comment]
@mkosmala does it have to be a plausible sounding name? @astopy @parrish as you'll be the ones using this mostly, do you have any strong feelings? Maybe we could just use the gaffer's name, since he's DEFINITELY not going anywhere...

**Comment by mkosmala** [comment]
@aliburchard Nope, it's just a username. Should be relatively shortish.

**Comment by aliburchard** [comment]
@mkosmala let's use "zooteam" if you think that's okay; otherwise use "Adam" or "astopy" -- we're going to link it to @astopy for now and hope he doesn't leave us any time soon. Do you need an email to tie it to?

**Comment by mkosmala** [comment]
Okay, MSI has changed its procedures (yet again). Soon MSI usernames will be tied tightly to the UMN usernames. So now they will only allow new users who have a UMN ID to be added at MSI.

That means:
(1) Yes, the user needs to be specifically tied to a person.
(2) That person needs to get a sponsored account through Craig.

If it's helpful, both Arfon and Chris Snyder already have accounts at MSI. For speed, use one of those? Otherwise, ask Craig to grant Adam a sponsored account. And then I can add him.

**Comment by mkosmala** [comment]
Okay, MSI has changed its procedures (yet again). Soon MSI usernames will
be tied tightly to the UMN usernames. So now they will only allow new users
who have a UMN ID to be added at MSI.

That means:
(1) Yes, the user needs to be specifically tied to a person.
(2) That person needs to get a sponsored account through Craig.

If it's helpful, both Arfon and Chris Snyder already have accounts at MSI.
For speed, use one of those? Otherwise, ask Craig to grant Adam a sponsored
account. And then I can add him.

**Comment by aliburchard** [comment]
Hey Margaret - 
Alright, we now have a sponsored account swan2220! Technically it's linked to me, but let's use that for now (can't access Arfon's or Chris S's MSI accounts because we don't have the passwords). 

Cheers,
Ali

**Comment by mkosmala** [comment]
Okay. So... you already have an MSI account, so just use yours then? (I assume swan2220 will be linked to your existing MSI user account...)

Also, should I delete Arfon's and Chris's accounts, then?

**Comment by aliburchard** [comment]
Ah, I assumed my MSI account dissolved when I lost my x500, sorry. Yup, let's delete Arfon's & Chris's accounts, and just use mine.
