### ISSUE TITLE
Should Discuss open a new tab?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Serengeti#81]
Let's say you want to classify an image, then discuss it on Talk, then use the Share/Tweet/Pin buttons. At present this is impossible, because once you hit Discuss, you can no longer get back to the "post classify" screen as it was loaded in the same tab. I think maybe Discuss should open in a new tab like Share, Tweet and Pin do. This way you can still come back and share etc. Alternatively, we should add the sharing functionalities into Talk. Or a button that lets you click back into the post-classify screen from Talk

**Comment by mrniaboc** [comment]
You can share/tweet/pin from Talk

**Comment by eatyourgreens** [comment]
Operation War Diary opens Talk and the blog in a new tab, for pretty much these reasons. For OWD, the problem was reloading the classification subject when you went to Talk and back again in the same tab. That really annoyed volunteers if they were in the middle of working on a page. Don't know if that would be a problem for Serengeti?

**Comment by alexbfree** [comment]
Discussed with Brian C and he agreed open in new tab is fine. Fixed in https://github.com/zooniverse/Serengeti/pull/87

**Comment by DarrenMcRoy** [comment]
We should reopen discussion about this. Users seem to prefer the old way, at least for this project.

I could do an informal poll on Talk to ask which way they like it better?
