### ISSUE TITLE
Site intro doesn't appear in mobile view

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Serengeti#98]
Just noticed that when I shrank my browser horizontally and the mobile-style view took over, the site intro vanishes.

Is this intentional?

**Comment by aweiksnar** [comment]
Yes, this is intentional. Supplementing the current tutorial with a slide-style one on mobile would be ideal, like in CWW, but for now it is hidden since it isn't usable while in the vertical orientation. If this is a concern perhaps we can chat with @heathv about making some images or gifs for a secondary one.

**Comment by DarrenMcRoy** [comment]
The only weird thing is that, if it's your first time to the site, it still loads the tutorial image with that wildebeest.

**Comment by aweiksnar** [comment]
True, however classifying that wildebeest image marks users as having completed the tutorial, and if they do so on mobile it will merit them as such and then they won't have to classify the wildebeest again should they choose to revisit the site on desktop

**Comment by DarrenMcRoy** [comment]
@heathv, would you be interested in working with me to do a mobile-style SS tutorial? How much effort do you think it would take?
